http:
  routers:
    sidecar-router:
      entryPoints:
        - "web"
        - "web-secure"
      rule: "Host(`{{ env "SIDECAR_DOMAIN"}}`)"
      service: "sidecar-service"
      tls: {}
  services:
    sidecar-service:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ env "SIDECAR_PORT"}}"

tcp:
  routers:
    helper-router:
      entryPoints:
        - "web-secure"
      rule: "HostSNI(`{{ env "HELPER_DOMAIN"}}`)"
      service: "helper-service"
      tls:
        passthrough: true

  services:
    helper-service:
      loadBalancer:
        servers:
          - address: "127.0.0.1:{{ env "HELPER_PORT"}}"
