tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

http:
  routers:
    service1:
      rule: "Host(`{{env "BASE_DOMAIN"}}`)"
      service: "service1"
      entryPoints:
        - "web-secure"
      tls:
        cert: "${CERT_PATH}"
        key: "${KEY_PATH}"
    service2:
      rule: "Host(`ipa.{{env "BASE_DOMAIN"}`)"
      service: "service2"
      entryPoints:
        - "web-secure"
      tls:
        cert: "${CERT_PATH}"
        key: "${KEY_PATH}"

  services:
    service1:
      loadBalancer:
        servers:
          - url: "http://localhost:17340"
    service2:
      loadBalancer:
        servers:
          - url: "http://localhost:17341"
