http:
  routers:
    sidecar-router:
      entryPoints:
        - "web"
        - "web-secure"
      rule: "Host(`{{ env "SIDECAR_DOMAIN"}}`)"
      service: "sidecar-service"
      tls: {}
    helper-router:
      entryPoints:
        - "web-secure"
      rule: "Host(`{{ env "HELPER_DOMAIN"}}`)"
      service: "helper-service"
      tls: {}
  services:
    sidecar-service:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ env "SIDECAR_PORT"}}"
    helper-service:
      loadBalancer:
        servers:
          - url: "http://localhost:{{ env "HELPER_PORT" }}"
