- name: Deploy updates to Draft
  hosts: all
  tasks:
    - name: Stop helper sidecar
      shell: >
        source .venv/bin/activate &&
        draft stop-helper-sidecar
      args:
        chdir: '{{ ansible_env.HOME }}/draft'
        executable: /bin/bash

    - name: Pull new commits from GitHub
      git:
        repo: 'https://github.com/private-attribution/draft.git'
        dest: '{{ ansible_env.HOME }}/draft'
        update: yes
    - name: Checkout and pull main branch
      command: git pull origin main
      args:
        chdir: '{{ ansible_env.HOME }}/draft'
    - name: Start helper sidecar
      shell: >
        source .venv/bin/activate &&
        draft start-helper-sidecar
        --identity {{ identity }}
        --root_domain {{ root_domain }}
        --helper_domain {{ helper_domain }}
        --sidecar_domain {{ sidecar_domain }}
        --config_path {{ ansible_env.HOME }}/draft/config
      args:
        chdir: '{{ ansible_env.HOME }}/draft'
        executable: /bin/bash
