name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321"
      SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU"
      SUPABASE_AUTH_GITHUB_CLIENT_ID: "foo"
      SUPABASE_AUTH_GITHUB_SECRET: "bar"


    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: supabase/setup-cli@v1
    - run: supabase start --workdir server
    - run: supabase db reset --workdir server

    - name: Install dependencies
      run: |
        pip install .
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install next
      run: npm --prefix server install next
    - name: Install requirements
      run: npm --prefix server install

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
